volumes:
  php_vol:
  db_sga_vol:
networks:
  sga_networks:
    driver: bridge
services:
  mysql:
    image: mysql:8.3.0
    environment: # variaveis de ambiente
      MYSQL_ROOT_PASSWORD: senha123456
      MYSQL_DATABASE: sga
      MYSQL_USER: sga_admin
      MYSQL_PASSWORD: PwdSga
    ports:
      - 3336:3306
    volumes:
      - db_sga_vol:/var/lib/mysql
    networks:
      - sga_networks

  web:
    image: php:7.3-apache
    environment:
      - APACHE_DOCUMENT_ROOT=/path/to/new/root
    volumes:
      - php_vol
    networks:
     - sga_networks

