version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: glpidb
      MYSQL_USER: glpi_user
      MYSQL_PASSWORD: glpi
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - glpi-network

  glpi:
    image: diouxx/glpi
    container_name: glpi
    depends_on:
      - mysql
    ports:
      - "80:80"
    networks:
      - glpi-network

volumes:
  mysql_data:

networks:
  glpi-network:
    driver: bridge
