version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: api-com-docker
    ports:
      5001:5001
    dependes_on:
      postgres:
        image: bitnami/postgresql:latest
        container_name: postgres
        ports:
          - "5432:5432"
        enviroment:
          POSTGRES_USER: postgres
          POSTGRES_PASSEORD: postgres
          POSTGRES_DB: api
        volumes: 
          - database:/var/lib/postgresql/data

volumes:
 - database  