services:
  apache:
    image: php:7.0.3-apache
    container_name: meu-apache
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/html/src
    ports:
      - "8080:80"
    restart: always
