Novosga\Entity\Agendamento:
    type: entity
    table: agendamentos
    indexes:
        agendamento_oid_index:
            columns: [ oid ]
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        data:
            type: date
            nullable: false
            column: data
        hora:
            type: time
            nullable: false
            column: hora
        dataConfirmacao:
            type: datetime
            nullable: true
            column: data_confirmacao
        oid:
            type: string
            nullable: true
            column: oid
            length: 36
        situacao:
            type: string
            nullable: false
            column: situacao
            length: 20
    manyToOne:
        cliente:
            targetEntity: Novosga\Entity\Cliente
            fetch: LAZY
            cascade: [persist]
            joinColumns:
                cliente_id:
                    referencedColumnName: id
        unidade:
            targetEntity: Novosga\Entity\Unidade
            fetch: LAZY
            joinColumns:
                unidade_id:
                    referencedColumnName: id
        servico:
            targetEntity: Novosga\Entity\Servico
            fetch: LAZY
            joinColumns:
                servico_id:
                    referencedColumnName: id
