Novosga\Entity\Atendimento:
    type: entity
    table: atendimentos
    repositoryClass: App\Repository\ORM\AtendimentoRepository
    manyToOne:
        pai:
            targetEntity: Novosga\Entity\Atendimento
            fetch: LAZY
            joinColumns:
                atendimento_id:
                    referencedColumnName: id
    oneToMany:
        codificados:
            targetEntity: Novosga\Entity\AtendimentoCodificado
            cascade: {  }
            fetch: LAZY
            mappedBy: atendimento
            orphanRemoval: false
            orderBy: null
