Novosga\Entity\Cliente:
    type: entity
    table: clientes
    repositoryClass: App\Repository\ORM\ClienteRepository
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: documento
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            length: 60
            nullable: false
        documento:
            type: string
            length: 30
            nullable: false
        email:
            type: string
            length: 80
            nullable: true
        telefone:
            type: string
            length: 25
            nullable: true
        dataNascimento:
            type: date
            nullable: true
            column: dt_nascimento
        genero:
            type: string
            length: 1
            nullable: true
        observacao:
            type: text
            nullable: true
    embedded:
        endereco:
            class: Novosga\Entity\Endereco
            columnPrefix: end_
