Novosga\Entity\Endereco:
    type: embeddable
    fields:
        pais:
            type: string
            length: 2
            nullable: true
        cep:
            type: string
            length: 25
            nullable: true
        estado:
            type: string
            length: 3
            nullable: true
        cidade:
            type: string
            length: 30
            nullable: true
        logradouro:
            type: string
            length: 60
            nullable: true
        numero:
            type: string
            length: 10
            nullable: true
        complemento:
            type: string
            length: 15
            nullable: true