Novosga\Entity\UsuarioMeta:
    type: entity
    table: usuarios_metadata
    repositoryClass: App\Repository\ORM\UsuarioMetadataRepository
    id:
        entity:
            associationKey: true
    manyToOne:
        entity:
            targetEntity: Novosga\Entity\Usuario
            fetch: LAZY
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
